name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install specific Black version
        run: |
          pip install black==25.1.0  # desired version here
      - name: Run Black check
        run: |
          black --check --verbose ./protograf
